networks:
  media-net:
    external: true

services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /opt/services/jellyfin/config:/config
      - /mnt/media/photos:/data/photos
    ports:
      - 8096:8096
    devices:
      - /dev/dri:/dev/dri
    networks:
      - media-net
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    restart: unless-stopped
